### PR TITLE
Finish translation of accessibility.md

### PR DESCRIPTION
**Pull request by r3sMetz**
Translated the missing parts of our recent translation.

### CODE REVIEW

**Comment by ph1p** [comment]
Could you please create a branch from the current master and add your changes? Because the most parts of this PR are already reviewed. This would be great! Thanks (:

**Comment by r3sMetz** [comment]
Stupid question, this isn't possible without creating a new fork+PR , right?

**Comment by ph1p** [comment]
> Stupid question: This isn't possible without creating a new fork+PR , right?
Try to merge the current master into this PR and push it again.

**Comment by r3sMetz** [comment]
Nothing exploded so far... but i think i've broke it :D

**Comment by ph1p** [comment]
Jep :D The easiest way to solve this little mistake are the following steps:

- pull the current de.reactjs.org master branch into your fork master branch
- create a new "a11y" branch
- add your changes
- create a PR

**Pull request closed without merging**
